Vagrant.configure("2") do |config|

  hostname = File.basename(Dir.getwd)
  config.vm.define "#{hostname}" do |app|
    app.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "4096"
      vb.cpus = 4
    end
    app.vm.hostname = "#{hostname}"
    app.vm.box = "bento/centos-7.3"
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
    app.vm.network "private_network", ip: "10.0.111.111"
    app.vm.network "forwarded_port", guest: 5000, host: 15000
    app.vm.network "forwarded_port", guest: 5001, host: 15001
    app.vm.network "forwarded_port", guest: 5002, host: 15002
    app.vm.provision "ansible" do |ansible|
      ansible.verbose  = "v"
      ansible.playbook = "playbook.yml"
      ansible.sudo = true
    end
  end
end
