# Require the reboot plugin. selinux need to reboot to make sure it is closed
require './vagrant-provision-reboot-plugin'
Vagrant.configure("2") do |config|
  config.vm.define "004-kolla-mul-controller" do |app|
    app.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "20480"
      vb.cpus = 8
    end

    app.vm.hostname = "004-kolla-mul-controller"
    app.vm.box = "bento/centos-7.3"
    if Vagrant.has_plugin?("vagrant-cachier")
      config.cache.scope = :box
      config.cache.synced_folder_opts = {
        type: :nfs,
        mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
      }
    end
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
    app.vm.network "private_network",  ip: "10.0.23.12"
    app.vm.network "private_network",  ip: "10.0.25.12"
    app.vm.network "forwarded_port", guest: 80,  host: 10080
    app.vm.network "forwarded_port", guest: 443, host: 10443
    app.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
    app.vm.provision "ansible" do |ansible|
      ansible.verbose  = "v"
      ansible.playbook = "playbook.yml"
      ansible.sudo = true
    end
    app.vm.provision :unix_reboot
  end
end
