# Require the reboot plugin. selinux need to reboot to make sure it is closed
require './vagrant-provision-reboot-plugin'
storage_num = 3
Vagrant.configure("2") do |config|
  storage_num.times do |i|
    file_to_disk = "./tmp/large_disk_#{i+1}.vdi"
    ip_last = 81 + i
    config.vm.define "008-#{i+1}-kolla-mul-storage" do |app|
      app.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "20480"
        vb.cpus = 4
        unless File.exist?(file_to_disk)
          vb.customize ['createhd', '--filename', file_to_disk, '--size', 500 * 1024]
        end
        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
      end

      app.vm.hostname = "008-#{i+1}-kolla-mul-storage"
      app.vm.box = "bento/centos-7.3"
      if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.scope = :box
        config.cache.synced_folder_opts = {
          type: :nfs,
          mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
        }
      end
      app.vm.box_check_update = false
      app.ssh.insert_key = false
      app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
      app.vm.network "private_network",  ip: "10.0.25.#{ip_last}"
      app.vm.network "private_network",  ip: "10.0.26.#{ip_last}"
      app.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
      app.vm.provision "ansible" do |ansible|
        ansible.verbose  = "v"
        ansible.playbook = "playbook.yml"
        ansible.sudo = true
      end
      app.vm.provision :unix_reboot
    end
  end
end
