Vagrant.configure("2") do |config|
  file_to_disk = './tmp/large_disk.vdi'
  hostname = File.basename(Dir.getwd)
  config.vm.define "#{hostname}" do |app|
    app.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "20480"
      vb.cpus = 8
      unless File.exist?(file_to_disk)
        vb.customize ['createhd', '--filename', file_to_disk, '--size', 500 * 1024]
      end
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
    end

    app.vm.hostname = "#{hostname}"
    app.vm.box = "bento/centos-7.3"
    if Vagrant.has_plugin?("vagrant-cachier")
      config.cache.scope = :box
      config.cache.synced_folder_opts = {
        type: :nfs,
        mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
      }
    end
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
    app.vm.network "private_network",  ip: "10.0.23.21"
    app.vm.network "private_network",  ip: "10.0.24.21"
    app.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
    app.vm.provision "ansible" do |ansible|
      ansible.verbose  = "v"
      ansible.playbook = "../config/base.yml"
      ansible.sudo = true
    end
    app.vm.provision "ansible" do |ansible|
      ansible.verbose  = "v"
      ansible.playbook = "../config/control.yml"
      ansible.sudo = true
    end
  end
end
