---                             # install base.yml first
- hosts: all
  sudo: yes
  vars:
    network_interface:          enp0s8
    neutron_external_interface: enp0s9
    kolla_internal_vip_address: "{{ '.'.join(vars['ansible_' + vars['network_interface']]['ipv4']['address'].split('.')[:3] + ['222']) }}"
    external_ip: "{{ '.'.join(vars['ansible_' + vars['neutron_external_interface']]['ipv4']['address'].split('.')[:3]) }}"
    ext_net_cidr:    "{{ external_ip }}.0/24"
    ext_net_range:   "start={{ external_ip }}.100,end={{ external_ip }}.200"
    ext_net_gateway: "{{ external_ip }}.1"
  tasks:
    - name: Find out the vm support
      shell: |
        egrep -c '(vmx|svm)' /proc/cpuinfo
      register: vm_num
      ignore_errors: yes
    - name: Ensure nova-compute.conf had folder
      file:
        path: /etc/kolla/config/nova
        state: directory
      when: vm_num.stdout|int == 0
    - name: Ensure nova-compute.conf had contents
      copy:
        src: nova-compute.conf
        dest: /etc/kolla/config/nova/nova-compute.conf
      when: vm_num.stdout|int == 0
    - name: Ensure config had folder
      file:
        path: /etc/kolla/config/
        state: directory
    - name: Ensure ceph.conf had contents
      copy:
        src: ceph.conf
        dest: /etc/kolla/config/ceph.conf
    - name: Modify the etc hosts file
      copy:
        src: hosts
        dest: /etc/hosts
        force: yes
    - name: Ensure the target folder existed
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /etc/kolla
        - /root/inventory
    - name: Get contents from /usr/share/kolla-ansible
      shell: |
        cp -r /usr/share/kolla-ansible/etc_examples/kolla/* /etc/kolla/
        cp -r /usr/share/kolla-ansible/ansible/inventory/* /root/inventory*
    - name: Modify /etc/kolla/globals.yml
      lineinfile:
        path: /etc/kolla/globals.yml
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^network_interface',          line: 'network_interface:          "{{ network_interface          }}"'}
        - { regexp: '^neutron_external_interface', line: 'neutron_external_interface: "{{ neutron_external_interface }}"'}
        - { regexp: '^kolla_internal_vip_address', line: 'kolla_internal_vip_address: "{{ kolla_internal_vip_address }}"'}
        - { regexp: '^keystone_admin_password',    line: 'keystone_admin_password: welcome'} # only source deploy can use this password
        - { regexp: '^openstack_release',          line: 'openstack_release: 4.0.3'}
        - { regexp: '^docker_namespace',           line: 'docker_namespace: lokolla'}
        - { regexp: '^kolla_install_type',         line: 'kolla_install_type: binary'}
        # - { regexp: '^enable_cinder',              line: 'enable_cinder: "yes"'}
        # - { regexp: '^enable_ceph',                line: 'enable_ceph: "yes"'}
        # - { regexp: '^enable_ceph_rgw',            line: 'enable_ceph_rgw: "yes"'}
    - name: Gen password for /etc/kolla/passwords.yml
      shell: |
        kolla-genpwd
    - name: Modify /usr/share/kolla-ansible/init-runonce
      lineinfile:
        path: /usr/share/kolla-ansible/init-runonce
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^EXT_NET_CIDR',    line: 'EXT_NET_CIDR="{{    ext_net_cidr    }}"'}
        - { regexp: '^EXT_NET_RANGE',   line: 'EXT_NET_RANGE="{{   ext_net_range   }}"'}
        - { regexp: '^EXT_NET_GATEWAY', line: 'EXT_NET_GATEWAY="{{ ext_net_gateway }}"'}
        - { regexp: '^IMAGE_URL=http', line: 'IMAGE_URL=http://10.0.111.111:5001/'}
        - { regexp: 'ssh-keygen -t rsa -f ~/.ssh/id_rsa', line: '    ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" '}
