---
- hosts: all
  sudo: yes

  vars:
    systemd_docker_config_directory: /etc/systemd/system/docker.service.d
    network_interface:          enp0s8
    neutron_external_interface: enp0s9
    kolla_internal_vip_address: "{{ '.'.join(vars['ansible_' + vars['network_interface']]['ipv4']['address'].split('.')[:3] + ['222']) }}"
    external_ip: "{{ '.'.join(vars['ansible_' + vars['neutron_external_interface']]['ipv4']['address'].split('.')[:3]) }}"
    ext_net_cidr:    "{{ external_ip }}.0/24"
    ext_net_range:   "start={{ external_ip }}.100,end={{ external_ip }}.200"
    ext_net_gateway: "{{ external_ip }}.1"
  tasks:
    - name: Install list of packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - epel-release
        - python-pip
        - python-devel
        - libffi-devel
        - gcc
        - openssl-devel
        - libselinux-python
        - ntp
    - name: Ensure the ssh folder exist under root
      file: path=/root/.ssh state=directory
    - name: Copy the ssh id_rsa
      copy:
        src: ../config/id_rsa
        dest: /root/.ssh/id_rsa
        force: yes
        mode: 0600
    - name: Copy the id_rsa.pub
      copy:
        src: ../config/id_rsa.pub
        dest: /root/.ssh/id_rsa.pub
        force: yes
        mode: 0644
    - name: Copy the authorized_keys
      copy:
        src: ../config/authorized_keys
        dest: /root/.ssh/authorized_keys
        force: yes
        mode: 0644
    - name: Make the root ssh client no checking
      lineinfile:
        path: /etc/ssh/ssh_config
        regexp: '^StrictHostKeyChecking'
        line: 'StrictHostKeyChecking no'
    - name: Make the root ssh remote workable
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin yes'
    - name: Make sure the root bashrc
      copy:
        src: ../config/bashrc
        dest: ~/.bashrc
        force: yes
    - name: Make sure the pip folder
      file:
        path: ~/.pip
        state: directory
    - name: pip mirror
      copy:
        src: ../config/pip.conf
        dest: ~/.pip/pip.conf
        force: yes
    - name: Install Pip Packages
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - python-openstackclient
        - ansible
        - kolla-ansible
    - name: Diable selinux
      selinux:
        state: disabled
    - name: Make sure some service is disabled
      systemd:
        state: stopped
        name: "{{ item }}"
      with_items:
        - firewalld
    - name: Find out the vm support
      shell: |
        egrep -c '(vmx|svm)' /proc/cpuinfo
      register: vm_num
      ignore_errors: yes
    - name: Ensure nova-compute.conf had folder
      file:
        path: /etc/kolla/config/nova
        state: directory
      when: vm_num.stdout|int == 0
    - name: Ensure nova-compute.conf had contents
      copy:
        src: ../config/nova-compute.conf
        dest: /etc/kolla/config/nova/nova-compute.conf
      when: vm_num.stdout|int == 0
    - name: Ensure config had folder
      file:
        path: /etc/kolla/config/
        state: directory
    - name: Ensure ceph.conf had contents
      copy:
        src: ../config/ceph.conf
        dest: /etc/kolla/config/ceph.conf
    - name: Make sure ntp is running
      systemd:
        state: started
        name: ntpd
    - name: Ensure the target folder existed
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /etc/kolla
        - /root/inventory
    - name: Get contents from /usr/share/kolla-ansible
      shell: |
        cp -r /usr/share/kolla-ansible/etc_examples/kolla/* /etc/kolla/
    - name: Get the deploy file
      copy:
        src: ../config/multinode
        dest: /root/inventory/multinode
        force: yes
    - name: Modify /etc/kolla/globals.yml
      lineinfile:
        path: /etc/kolla/globals.yml
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^network_interface',          line: 'network_interface:          "{{ network_interface          }}"'}
        - { regexp: '^neutron_external_interface', line: 'neutron_external_interface: "{{ neutron_external_interface }}"'}
        - { regexp: '^kolla_internal_vip_address', line: 'kolla_internal_vip_address: "{{ kolla_internal_vip_address }}"'}
        - { regexp: '^keystone_admin_password',    line: 'keystone_admin_password: welcome'} # only source deploy can use this password
        - { regexp: '^openstack_release',          line: 'openstack_release: 4.0.3'}
        - { regexp: '^docker_registry',            line: 'docker_registry: 10.0.111.111:5000'}
        - { regexp: '^docker_namespace',           line: 'docker_namespace: lokolla'}
        - { regexp: '^kolla_install_type',         line: 'kolla_install_type: binary'}
        - { regexp: '^enable_cinder',              line: 'enable_cinder: "yes"'}
        - { regexp: '^enable_ceph',                line: 'enable_ceph: "yes"'}
        - { regexp: '^enable_ceph_rgw',            line: 'enable_ceph_rgw: "yes"'}
    - name: Gen password for /etc/kolla/passwords.yml
      shell: |
        kolla-genpwd
    - name: Modify /usr/share/kolla-ansible/init-runonce
      lineinfile:
        path: /usr/share/kolla-ansible/init-runonce
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^EXT_NET_CIDR',    line: 'EXT_NET_CIDR="{{    ext_net_cidr    }}"'}
        - { regexp: '^EXT_NET_RANGE',   line: 'EXT_NET_RANGE="{{   ext_net_range   }}"'}
        - { regexp: '^EXT_NET_GATEWAY', line: 'EXT_NET_GATEWAY="{{ ext_net_gateway }}"'}
        - { regexp: 'ssh-keygen -t rsa -f ~/.ssh/id_rsa', line: '    ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" '}
    - name: put the image for init-runonce to use
      copy:
        src: "{{ item.src}}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: 'tools/cirros-0.3.4-x86_64-disk.img',           dest: '/usr/share/kolla-ansible/'}
        - { src: 'tools/xenial-server-cloudimg-amd64-disk1.img', dest: '/usr/share/kolla-ansible/'}
        - { src: 'tools/create_ubuntu_image.sh',           dest: '/usr/share/kolla-ansible/'}
    - name: Modify the etc hosts file
      copy:
        src: ../config/hosts
        dest: /etc/hosts
        force: yes
