Vagrant.configure("2") do |config|

  config.vm.define "kolla-multi-repo" do |app|
    app.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "4096"
      vb.cpus = 4
    end
    app.vm.hostname = "kolla-multi-repo"
    app.vm.box = "bento/centos-7.3"
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
    app.vm.network "private_network",  ip: "10.0.77.111"
    app.vm.provision "ansible" do |ansible|
      ansible.verbose  = "v"
      ansible.playbook = "playbook.yml"
      ansible.sudo = true
    end
  end
end
